import CallToAction from "@/components/CallToAction";
import StatItem from "@/components/StatItem";
import { Colors } from "@/constants/colors";
import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import { useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import FeatureCard from "../components/FeatureCard";
import PrimaryButton from "../components/PrimaryButton";
import SideMenu from "../components/SideMenu";
import TrustBadge from "../components/TrustBadge";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <View style={{ flex: 1, backgroundColor: Colors.background }}>
      {/* PAGE CONTENT */}
      <ScrollView
        style={styles.container}
        contentContainerStyle={{ paddingTop: 90 }}
      >
        {/* HERO SECTION */}
        <View style={styles.hero}>
          <View style={styles.badge}>
            <Ionicons name="flash-outline" size={14} color="#55F2C4" />
            <Text style={styles.badgeText}> NEXT GEN WEB PROTECTION</Text>
          </View>

          <Text style={styles.title}>
            Secure Your Web{"\n"}
            Infrastructure with{"\n"}
            <Text style={styles.glow}>Black Cat</Text>
          </Text>

          <Text style={styles.desc}>
            Automated security scans targeting common vulnerabilities like XSS,
            SQL Injection, and Auth weaknesses.
          </Text>
        </View>

        <PrimaryButton title="Start Free Scan" />

        <View style={styles.secondaryBtn}>
          <Text style={styles.secondaryText}>Live Demo</Text>
        </View>

        {/* TRUST BADGES */}
        <View style={styles.trustContainer}>
          <TrustBadge label="Trusted by Forbes" />
          <TrustBadge label="ISO 27001" />
          <TrustBadge label="SOC2 Compliant" />
          <TrustBadge label="G2 Leader" />
        </View>

        {/* SECURITY SUITE SECTION */}
        <View style={styles.suiteSection}>
          <Text style={styles.suiteTitle}>Full-Stack Security Suite</Text>
          <Text style={styles.suiteDesc}>
            Everything you need to monitor, detect, and fix vulnerabilities
            before they can be exploited.
          </Text>
        </View>

        {/* FEATURES */}
        <View style={styles.features}>
          <FeatureCard
            Icon={<Ionicons name="scan-outline" size={32} color="#0F1C2E" />}
            title="Automated Scanner"
            desc="Deep crawl engine detecting XSS, SQLi, and misconfigurations with zero false positives."
          />

          <FeatureCard
            Icon={
              <Ionicons name="bar-chart-outline" size={32} color="#0F1C2E" />
            }
            title="Analytics Dashboard"
            desc="Interactive visual data representations for real-time risk assessment and trend monitoring."
          />

          <FeatureCard
            Icon={<Ionicons name="flash-outline" size={32} color="#0F1C2E" />}
            title="AI Reports"
            desc="Intelligent, context-aware summaries generated by AI to turn complexity into clarity."
          />

          <FeatureCard
            Icon={
              <MaterialCommunityIcons
                name="robot-outline"
                size={32}
                color="#0F1C2E"
              />
            }
            title="24/7 AI Chatbot"
            desc="Expert-level security assistance integrated directly into your workflow for instant support."
          />
        </View>

        {/* STATS SECTION */}
        <View style={styles.statsSection}>
          <StatItem value="10M+" label="Scans Performed" />
          <StatItem value="99.9%" label="Detection Accuracy" />
          <StatItem value="50ms" label="Alert Latency" />
        </View>

        <CallToAction />

        {/* FOOTER */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            © 2024 Black Cat Security. Built for hackers by defenders.
          </Text>
        </View>
      </ScrollView>

      {/* TOGGLE MENU */}
      {menuOpen && <SideMenu onClose={() => setMenuOpen(false)} />}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.background,
    paddingHorizontal: 20,
  },

  hero: {
    alignItems: "center",
    marginTop: 20,
  },

  title: {
    color: Colors.textPrimary,
    fontSize: 38,
    fontWeight: "bold",
    lineHeight: 40,
    textAlign: "center",
  },

  glow: {
    color: Colors.primary,
    textShadowColor: Colors.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },

  desc: {
    color: Colors.textSecondary,
    marginTop: 16,
    lineHeight: 22,
    textAlign: "center",
  },

  secondaryBtn: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 12,
  },

  secondaryText: {
    color: Colors.textPrimary,
  },

  trustContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 40,
  },

  suiteSection: {
    marginTop: 80,
    paddingHorizontal: 10,
    alignItems: "center",
  },

  suiteTitle: {
    color: Colors.textPrimary,
    fontSize: 26,
    fontWeight: "bold",
    textAlign: "center",
  },

  suiteDesc: {
    color: Colors.textSecondary,
    marginTop: 12,
    lineHeight: 22,
    textAlign: "center",
    maxWidth: 300,
  },

  features: {
    marginTop: 40,
  },

  statsSection: {
    marginTop: 80,
    alignItems: "center",
  },

  footer: {
    marginTop: 60,
    paddingBottom: 40,
    alignItems: "center",
  },

  footerText: {
    color: Colors.textSecondary,
    fontSize: 12,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 30,
    backgroundColor: "rgba(77, 255, 243, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(18, 185, 160, 0.5)",
    shadowColor: "#44c29c", 
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 8,
    marginBottom: 19,
  },

  badgeText: {
    color: "#4fdbb1",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 1,
  },
});
